// Dev-time generator. Reads the single source of truth (the frontend catalog)
// and emits a token-lean projection the backend can ship without frontend src.
// Re-run with `npm run build:films` whenever the catalog changes.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { FILMS } from "../../frontend/src/data/catalog.js";

const here = dirname(fileURLToPath(import.meta.url));
const SYNOPSIS_MAX = 200;

const projected = FILMS.map((f) => ({
  id: f.id,
  title: f.title,
  year: f.year ?? null,
  genre: f.genre ?? null,
  director: f.director ?? null,
  synopsis: (f.synopsis || "").slice(0, SYNOPSIS_MAX),
}));

const out = `// GENERATED by scripts/build-films.mjs — do not edit by hand.
// Run \`npm run build:films\` to regenerate from frontend/src/data/catalog.js.
export const FILMS = ${JSON.stringify(projected, null, 2)};
`;

writeFileSync(join(here, "../data/films.js"), out);
console.log(`wrote backend/data/films.js (${projected.length} films)`);
